spring:
  # ??Redis
  redis:
    host: 192.168.58.212
    port: 6379
    password: 12345678
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: 1000
